Repository Clear-Sight/virtual-gimbal-camera, pull requests merged in 2021-04, with the labels that each got.

#44 rm cython
  .github/workflows/development-tests.yml
  .github/workflows/master-tests.yml
  build.sh
  clean.sh
  run.sh
  setup.py
  vgc/__main__.py
  vgc/primes.pyx
Labels: enhancement

#49 Feature output adapter
  vgc/__main__.py
  vgc/cameraFilter.py
  vgc/io/outputAdapter.py
Labels: enhancement

#48 Feature autopilot
  config.json
  requirements.txt
  tests/test_autopilot_adapter.py
  tests/test_cameraFilter.py
  tests/test_viewController.py
  vgc/autopilot_adapter.py
Labels: enhancement

#51 Feature threading integration
  vgc/__main__.py
  vgc/cameraFilter.py
  vgc/io/inputAdapter.py
  vgc/io/outputAdapter.py
  vgc/pipeline.py
  vgc/viewController.py
Labels: enhancement

#46 Review - Viewcontroller
  .coveragerc
  requirements.txt
  tests/test_viewController.py
  vgc/viewController.py
Labels: enhancement

#52 name change from camel to snake case on files
  install.sh
  requirements.txt
  setup.py
  tests/test_cameraFilter.py
  tests/test_viewController.py
  vgc/__main__.py
  vgc/camera_filter.py
  vgc/input_regulator.py
  vgc/io/input_adapter.py
  vgc/io/output_adapter.py
  vgc/pipeline.py
  vgc/view_controller.py
Labels: invalid

#57 Feature inputadapter
  config.json
  vgc/input_regulator.py
  vgc/io/input_adapter.py
  vgc/io/output_adapter.py
  vgc/pipeline.py
  vgc/view_controller.py
Labels: enhancement

#58 Intgration fixes
  config.json
  result.avi
  run.sh
  vgc/__main__.py
  vgc/camera_filter.py
  vgc/filter.py
  vgc/io/adapter.py
  vgc/io/input_adapter.py
  vgc/io/output_adapter.py
  vgc/pipeline.py
  vgc/view_controller.py
Labels: enhancement

#64 Demo
  config.json
  tests/test_camera_filter.py
  tests/test_view_controller.py
  vgc/camera_filter.py
  vgc/config.py
  vgc/io/input_adapter.py
  vgc/pipeline.py
  vgc/view_controller.py
Labels: bug

#65 readme update
  README.md
Labels: documentation

#70 fixes to get the viewcontroller_fast to integrate with sys
  tests/test_view_controller.py
  tests/test_view_controller_fast.py
  vgc/pipeline.py
  vgc/view_controller_fast.py
Labels: enhancement

#71 added zoom
  vgc/io/input_adapter.py
  vgc/pipeline.py
Labels: enhancement

#72 Feature daemon
  install.sh
Labels: enhancement

#81 Feature logging
  config.json
  vgc/log.py
  vgc/pipeline.py
Labels: enhancement

#87 Feature camerafilter roll
  vgc/camera_filter.py
Labels: enhancement
